name: third_eye
description: "A new Flutter project."

# This prevents accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6
  path: ^1.9.0
  tflite_flutter: ^0.11.0
  flutter_tts: ^4.2.1
  image_picker: ^1.1.2
  image: ^3.0.1  # Make sure to check for the latest version
  path_provider: ^2.1.5
  permission_handler: ^11.0.0
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  # Add this section to include the model and labels as assets
  assets:
     - assets/model.tflite
     - assets/model_unquant.tflite
     - assets/labels.txt

